connection:
    path: /
    controller: App\Controller\ConnectionController::index

subscribe:
    path: /subscribe
    controller: App\Controller\SubscribeController::index


#index:
#    path: /
#    controller: App\Controller\DefaultController::index
